detector:
  type: "yolo"

  min_area_ratio: 0.002
  max_area_ratio: 0.20
  aspect_min: 2.0
  aspect_max: 6.5

  weights: "runs/detect/plate/weights/best.pt"
  conf: 0.25
  iou: 0.45
  img_size: 640

ocr:
  # easyocr | tesseract | tesseract_fast
  engine: "easyocr"
  languages: ["en"]
  tesseract_lang: "eng"

  fast:
    cut_blue_auto: false
    resize_fx: 2.1
    oem: 3

# KLUCZ: crop jak w demo (tight bbox)
crop:
  pad_x_ratio: 0.0
  pad_y_ratio: 0.0

postprocess:
  uppercase: true
  strip_spaces: true
  allowed_chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  plate_regex: "^[A-Z]{1,3}[A-Z0-9]{4,5}$"

access_control:
  sqlite_path: "data/plates.db"
